server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bookfair?createDatabaseIfNotExist=true
    username: root
    password: .Bolha1000
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
  jackson:
    default-property-inclusion: non_null